[project]
name = "nba-guesser"
version = "0.1.0"
description = "NBA guessing game where you guess the player by height, team, conference, division position, jersey number, and age!"

readme = "README.md"
authors = [
    { name = "Tyler Walsh", email = "tjwalsh@udel.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "datetime>=6.0",
    "nba-api>=1.11.4",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pylint>=4.0.6",
    "ruff>=0.16.2",
]

[project.scripts]
nba-guesser = "nba_guesser:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
